import tensorflow as tf

pong = {"env_name": 'Pong-v0',
        'n_epochs': 1,
        "batch_size": 6,
        "optimizer": tf.train.AdamOptimizer,
        'learning_rate': 1e-3,
        'beta': 0.9,
        'device': '/CPU:0',
        'list_action': [0, 2, 3],
        'path': '/pong',
        "nb_agents": 1,
        'n_actions': 3,
        "input_W": 210,
        'input_H': 160,
        'input_C': 3,
        'n_hidden_layers': 1,
        'n_hidden_layers_nodes': 32,
        'keys_to_action' : None
        }


CarRacing = {"env_name": 'Enduro-v0',
        'n_epochs': 1,
        "batch_size": 6,
        "optimizer": tf.train.AdamOptimizer,
        'learning_rate': 1e-4,
        'beta': 0.9,
        'device': '/CPU:0',
        'list_action': [0, 1, 8, 7, 3, 6, 2, 5, 4],
        'path': '/CarRacing',
        "nb_agents": 1,
        'n_actions': 9,
        "input_W": 210,
        'input_H': 160,
        'input_C': 3,
        'n_hidden_layers': 1,
        'n_hidden_layers_nodes': 32,
        'keys_to_action' : {(): 0,
                            (32,): 1,
                            (32, 97): 8,
                            (32, 100): 7,
                            (97,): 3,
                            (97, 115): 6,
                            (100,): 2,
                            (100, 115): 5,
                            (115,): 4,
                            (97, 100): 0,
                            (32, 97, 100): 1
                            }
        }
